name: MyLIT
description: "Um app de to-do list ultra-simples e 100% local."

publish_to: 'none' # Remove this line if you decide to publish

version: 0.0.00+1

environment:
  sdk: '>=3.3.0' # Atualizado para a versão mais recente do Dart

dependencies:
  flutter:
    sdk: flutter

  # --- Nossas Dependências Essenciais ---

  # O Hive é o nosso banco de dados local. É super rápido e leve.
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Precisamos disso para encontrar o local correto no celular para salvar o banco.
  path_provider: ^2.1.3

  # Para criar IDs únicos para cada tarefa, facilitando a migração.
  uuid: ^4.4.0

  # Para ícones bonitos
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0 # Sua versão mais recente

  # --- PACOTE DO ÍCONE (NOVO!) ---
  # Este pacote vai gerar todos os ícones para nós automaticamente.
  flutter_launcher_icons: ^0.13.1
  

flutter:
  uses-material-design: true

# --- CONFIGURAÇÃO DO ÍCONE (NOVO!) ---
# O Flutter vai ler isso para criar os ícones.
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png" # Caminho para o seu PNG principal
  adaptive_icon_background: "#00000000" # FUNDO TRANSPARENTE (como pedido)
  adaptive_icon_foreground: "assets/icon/icon_foreground.png" # Seu PNG sem fundo

